// ACTIONS
export const SIGNUP_ACTION = 'SIGNUP_ACTION';
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

// MUTATIONS
export const SET_USER_TOKEN_DATA_MUTATION = 'SET_USER_TOKEN_DATA_MUTATION';

// GETTERS
export const USER_ACCESS_TOKEN_GETTER = 'USER_ACCESS_TOKEN_GETTER';
export const ORGANIZATION_ID_GETTER = 'ORGANIZATION_ID_GETTER';