export const BASE_URL = 'http://localhost:2000';
export const SIGNUP_URL = BASE_URL + '/api/v1/auth/signup';
export const LOGIN_URL = BASE_URL + '/api/v1/auth/login';
export const ORGANIZATION_DETAILS_URL = BASE_URL + '/api/v1/organizations';
export const ALL_AGENTS = BASE_URL + '/api/v1/agents';
export const ALL_DEPARTMENTS = BASE_URL + '/api/v1/departments';
export const ASSIGNED_USERS_PART = 'assigned-users';
export const ALL_CHANNELS = BASE_URL + '/api/v1/channels'
export const ALL_MESSAGES = BASE_URL + '/api/v1/messages'
export const ALL_EXTERNAL_CHATS = BASE_URL + '/api/v1/chats/external'